macos_titlebar_color background
hide_window_decorations no
font_family SF Mono

font_size 12.0

disable_ligatures always

cursor_shape beam
cursor_stop_blinking_after 0

scrollback_lines 10000

copy_on_select yes

initial_window_height 768
initial_window_width 1024

enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell yes
bell_on_tab yes

remember_window_size no

enabled_layouts tall,stack

window_border_width 0.5

clear_all_shortcuts yes
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+q quit
map cmd+return toggle_fullscreen
map f5 load_config_file
map cmd+- decrease_font_size
map cmd+= increase_font_size
map cmd+0 restore_font_size

detect_urls yes
url_style curly
confirm_os_window_close 0

window_padding_width 10

# background            #000000
# foreground            #8fa1a6
# cursor                #c5c8c6
# selection_foreground  #1c1f24
# selection_background  #5a7a7f
# color0                #1b1b1b
# color8                #5f6a70
# color1                #b56a6a
# color9                #d27d7d
# color2                #7fa37f
# color10               #9bbf9b
# color3                #c7a96b
# color11               #d8bb84
# color4                #7a9cc6
# color12               #92b0d8
# color5                #a88fb8
# color13               #c0a4d4
# color6                #6fa6a6
# color14               #88bcbc
# color7                #c5c8c6
# color15               #e5e9f0

# Linkarzu (from screenshot)
background            #000000
foreground            #c0caf5
cursor                #b4a4e8
cursor_text_color     #16131f
selection_foreground  #e0def4
selection_background  #33324a
color0                #1a1726
color8                #414868
color1                #f7768e
color9                #f7768e
color2                #9ece6a
color10               #b9f27c
color3                #e0af68
color11               #e8c08a
color4                #7aa2f7
color12               #8db0ff
color5                #bb9af7
color13               #c8b0ff
color6                #7dcfff
color14               #a4dbff
color7                #c0caf5
color15               #ffffff
